[package]
name = "gotatun-cli"
description = "an implementation of the WireGuardÂ® protocol designed for portability and speed"
version = "0.1.0"
authors = [
    "Noah Kennedy <nkennedy@cloudflare.com>",
    "Andy Grover <agrover@cloudflare.com>",
    "Jeff Hiner <jhiner@cloudflare.com>",
    "Mullvad VPN",
]
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
categories = ["network-programming", "command-line-utilities"]
keywords = ["wireguard", "vpn"]
readme = "../README.md"

[target.'cfg(unix)'.dependencies]
daemonize = "0.4.1"
clap = { version = "3.1.6", features = ["env"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.9"
tracing-appender = "0.2.1"
log = "0.4"
tokio = { version = "1.43.0", features = ["full"] }

[target.'cfg(unix)'.dependencies.gotatun]
version = "0.1.0"
path = "../gotatun"
features = ["device", "tun"]
