[package]
name = "gotatun-cli"
description = "an implementation of the WireGuardÂ® protocol designed for portability and speed"
version = "0.2.0"
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
categories = ["network-programming", "command-line-utilities"]
keywords = ["wireguard", "vpn"]
readme.workspace = true

[[bin]]
name = "gotatun"
path = "src/main.rs"

[target.'cfg(unix)'.dependencies]
daemonize = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = ["full"] }
eyre = { workspace = true }
libc = { workspace = true }
nix = { workspace = true, features = [
    "fs",
    "time",
    "user",
    "socket",
    "uio",
    "net",
] }
gotatun = { workspace = true, features = ["device", "tun"] }