---
name: Nix - Check lint and format
on:
  pull_request:
    paths:
      - .github/workflows/nix-check.yml
      - '**/*.nix'
  workflow_dispatch:

permissions: {}

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Nix
        uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0

      - name: Check formatting
        run: nix run nixpkgs#nixfmt-tree -- --ci

      - name: Check for unused code
        run: nix run nixpkgs#deadnix -- --fail

      - name: Check for antipatterns
        run: nix run nixpkgs#statix check
